### ISSUE TITLE
Running mfisthtools with no 'off' clusters

### ISSUE THREAD

**Issue by AlexanderAivazidis** [AllenInstitute/mfishtools#2]
Hi!

I am trying to run mfishtools with no 'off' clusters and I get no genes back from the filterPanelGenes function. I think it might be related to the 'maxOff' parameter that is by default set to 50. 
In line 218 of your code you set the constraint maxExprOff<=maxOff
But before that in line 203 you set maxExprOff <- maxExprOn*Inf, for the case that there are no off clusters. Is there a minus missing?

Thanks

Alexander

**Comment by jeremymiller** [comment]
Hi Alexander!
Thanks for pointing this out.  It should be fixed now.  Sorry for the delay at getting back to you--I didn't receive a notification about this issue and forgot to check.  
Best,
Jeremy
