### ISSUE TITLE
why can't load library?

### ISSUE THREAD

**Issue by peachgong** [AllenInstitute/mfishtools#4]
It shows 
library(mfishtools)
Error in library(mfishtools) : there is no package called ‘mfishtools’

**Comment by jeremymiller** [comment]
If you haven't yet, first try installing the R library as shown on the main page.  There are two methods, so if one doesn't work, then try the other.  If neither work, could you please try installing the most recent release version?  As far as I know, no one else has run into this issue so it is possible it is something I have accidentally introduced into the code recently.  If none of these options solve it, please let me know and I'll see if I can reproduce the issue in a fresh R installation.

**Comment by peachgong** [comment]
work now. Just restart everything. So weird. 

Thanks!
