### ISSUE TITLE
what is the package called 'GO.db'?

### ISSUE THREAD

**Issue by peachgong** [AllenInstitute/mfishtools#5]
I tried to run the demo. In the step which uses the greedy algorithm to build a marker gene panel, it shows error as follow:

_fishPanel <- buildMappingBasedMarkerPanel(
+   mapDat        = normDat[runGenes,kpSamp],     # Data for optimization
+   medianDat     = medianExpr[runGenes,kpClust], # Median expression levels of relevant genes in relevant clusters
+   clustersF     = cl[kpSamp],                   # Vector of cluster assignments
+   panelSize     = 30,                           # Final panel size
+   currentPanel  = startingGenePanel,            # Starting gene panel
+   subSamp       = 15,                           # Maximum number of cells per cluster to include in analysis (20-50 is usually best)
+   optimize      = "CorrelationDistance",        # CorrelationDistance maximizes the cluster distance as described
+   clusterDistance = clusterDistance,            # Cluster distance matrix
+   percentSubset = 50                            # Only consider a certain percent of genes each iteration to speed up calculations (in most cases this is not recommeded)
+ )
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘GO.db’_

Other steps went through well, except 1278 total genes instead of 1309 pass constraints prior to binary score calculation in the previous 'filterPanelGenes' step. What is the package named 'G0.db' here ?

**Comment by peachgong** [comment]
googled and installed as 
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("GO.db")

**Comment by jeremymiller** [comment]
I'll add this requirement to the main page readme so others can avoid this issue.
